### ISSUE TITLE
Can't compile shaders in Edit mode

### ISSUE THREAD

**Issue by Goshido** [baldurk/renderdoc#3448]
## Description

I'm using _Vulkan + HLSL_ workflow. After editing shader and press compile `DXC` report compilation error:

```txt
Running "D:/Development/VulkanSDK/1.3.290.0/Bin/dxc.exe" -T ps_6_0 -E PS -spirv -fspv-target-env=vulkan1.1 -Fo C:/Users/Goshido/AppData/Local/Temp/shader_output C:/Users/Goshido/AppData/Local/Temp/shader_input
error: missing entry point definition


Process crashed with code -2147467259.
Output file is 0 bytes
```

I also noticed that previous _RenderDoc v1.34_ showed exactly the same compilation flag information:

```bash
-T {hlsl_stage2}_6_0 -E {entry_point} -spirv -fspv-target-env={vulkan_ver}  -E PS -T ps_6_8 -HV 2021 -spirv 
-fvk-use-dx-layout -fspv-reduce-load-size -fspv-target-env=vulkan1.1 -enable-16bit-types -WX -I tools\editor\hlsl
-I tools\editor\include -I app\src\main\hlsl -I app\src\main\cpp\include\pbr -Od -fspv-debug=vulkan-with-source
-Fo tools\editor\editor-assets\shaders\blit.ps.spv -Qembed_debug
```

Current _RenderDoc v1.35_ shows less information:

```bash
-T {hlsl_stage2}_6_0 -E {entry_point} -spirv -fspv-target-env={vulkan_ver}
```

## Steps to reproduce

1. Take the following shader code:

`blit_program.ps`:

```cpp
#include "blit_program.inc"
#include "color_space.ps"
#include "srgb_program.inc"


// 1.0H / 2.4H
#define INVERSE_GAMMA           4.16667e-1F

[[vk::constant_id ( CONST_INVERSE_GAMMA )]]
float const                     g_inverseGamma = INVERSE_GAMMA;

[[vk::binding ( BIND_IMAGE, SET_BLIT )]]
Texture2D<float32_t4>           g_image:        register ( t0 );

[[vk::binding ( BIND_SAMPLER, SET_BLIT )]]
SamplerState                    g_sampler:      register ( s0 );

struct InputData
{
    [[vk::location ( ATT_SLOT_UV )]]
    noperspective float32_t2    _uv:            UV;
};

//----------------------------------------------------------------------------------------------------------------------

float32_t4 PS ( in InputData inputData ): SV_Target0
{
    float16_t3 const color = (float16_t3)g_image.SampleLevel ( g_sampler, inputData._uv, 0.0F ).xyz;
    return float32_t4 ( LinearToSRGB ( color, (float16_t)g_inverseGamma ), 1.0F );
}
```

`color_space.ps`:

```cpp
#ifndef COLOR_SPACE_PS
#define COLOR_SPACE_PS


float32_t3 LinearToSRGB ( in float16_t3 ldr, in float16_t inverseGamma )
{
    // See https://entropymine.com/imageworsener/srgbformula/
    float16_t3 const a = ldr * 12.92H;
    float16_t3 const b = 1.055H * pow ( ldr, inverseGamma ) - 0.055H;
    return (float32_t3)lerp ( a, b, (float16_t3)( ldr > 3.1308e-3H ) );
}


#endif // COLOR_SPACE_PS
```

`blit_program.inc`:

```cpp
#ifndef BLIT_PROGRAM_INC
#define BLIT_PROGRAM_INC


#define ATT_SLOT_UV     0

#define SET_BLIT        0
#define BIND_IMAGE      0
#define BIND_SAMPLER    1


#endif // BLIT_PROGRAM_INC
```

`srgb_program.inc`:

```cpp
#ifndef SRGB_PROGRAM_INC
#define SRGB_PROGRAM_INC


#define CONST_INVERSE_GAMMA     0


#endif // SRGB_PROGRAM_INC
```

2. Compile it with the following flags:

```txt
dxc.exe                                                     ^
    -HV 2021                                                ^
    -spirv                                                  ^
    -fvk-use-dx-layout                                      ^
    -fspv-reduce-load-size                                  ^
    -fspv-target-env=vulkan1.1                              ^
    -enable-16bit-types                                     ^
    -WX                                                     ^
    -I tools\editor\hlsl                                    ^
    -I tools\editor\include                                 ^
    -I app\src\main\hlsl                                    ^
    -I app\src\main\cpp\include\pbr                         ^
    -Od                                                     ^
    -fspv-debug=vulkan-with-source                          ^
    -E PS                                                   ^
    -T ps_6_8                                               ^
    -Fo tools\editor\editor-assets\shaders\blit.ps.spv      ^
    tools\editor\hlsl\blit.ps
```

3. Use this program and made capture.
4. Try to edit program `blit_program.ps` by multiplying `color` variable by `0.5H`.

```cpp
...

float32_t4 PS ( in InputData inputData ): SV_Target0
{
    float16_t3 const color = (float16_t3)g_image.SampleLevel ( g_sampler, inputData._uv, 0.0F ).xyz;
    return float32_t4 ( LinearToSRGB ( color * 0.5H, (float16_t)g_inverseGamma ), 1.0F ); <--------------------------
}
```

5. Press apply changes.

**Problem:** Compilation fails:

```txt
Running "D:/Development/VulkanSDK/1.3.290.0/Bin/dxc.exe" -T ps_6_0 -E PS -spirv
-fspv-target-env=vulkan1.1 -Fo C:/Users/Goshido/AppData/Local/Temp/shader_output
C:/Users/Goshido/AppData/Local/Temp/shader_input
error: missing entry point definition


Process crashed with code -2147467259.
Output file is 0 bytes
```

**Expected:** Compilation success.

## Environment

* RenderDoc version: _1.35_
* Operating System: _Windows 11 Pro (23H2, Build 22631.4169)_
* Graphics API: _Vulkan 1.1_
* GPU: _NVIDIA GeForce RTX 4080_, game ready driver _561.09_
* DXC: 
  - _RenderDoc_ uses binary from official _Vulkan SKD 1.3.290.0_, _v1.8.0.4650_(`49d1ae9a0`)
  - _SPIR-V_ blobs are compiled with _v1.8.2407.10091_ from commit `75ff50caa046a054747ae15b5c1910a4c8aa1917`

## Additional information.

The video with problem:

https://github.com/user-attachments/assets/f0ef8f84-19f0-4230-9219-11175e0bf62c

**Comment by baldurk** [comment]
I can't reproduce this. I compiled the shaders as directed and the command line for the editing works in v1.34 and v1.35, though it fails due to the compiler bug you reported before in #3425 which is not a RenderDoc issue.

It would be easier if you could share your capture to reproduce the problem. Ideally one made in v1.34 which works and one made in v1.35 which breaks since you say it is a regression between versions.

**Comment by Goshido** [comment]
Sure. Here is captures:

From [_RenderDoc v1.34_](https://github.com/user-attachments/files/17176241/renderdoc-1.34.zip).

From [_RenderDoc v1.35_](https://github.com/user-attachments/files/17176306/renderdoc-1.35.zip).

**Comment by baldurk** [comment]
I get the failure to edit which seems to be caused by a broken shader - but both captures are equally broken for me so I'm presumably not seeing the same thing as you. Loading the v1.34 capture in either v1.34 or v1.35 is broken in exactly the same way as the v1.35 capture.

You're saying that this works in v1.34 with that capture, which draw exactly works in v1.34? does it also work if you load that working capture in v1.35?

**Comment by Goshido** [comment]
> You're saying that this works in v1.34 with that capture, which draw exactly works in v1.34?

I double checked v1.34 behavior. It turns out that error exactly the same as in v1.35. So it's not a regression but the same bug.

>  does it also work if you load that working capture in v1.35?

No. It doesn't work. Compilation error happens as described in the issue.

It looks like the _SPIR-V_ blobs from new _DXC_ trigger compilation error in the _RenderDoc_. I mean new _DXC_ fixes "shader source with define only includes" but breaks shader compilation. Maybe the problem is in _SPIR-V_ blobs itself? In _RenderDoc_ module which parses _SPIR-V_ and extracts shader source information and compilation flags?

Here is blobs from old and new _DXC_: [SPIR-V blobs.zip](https://github.com/user-attachments/files/17177782/SPIR-V.blobs.zip). Would you kindly run _RenderDoc_ under debugger and compare outcome for that _SPIR-V_ blobs?

**Comment by baldurk** [comment]
So you're saying that when you said it was working in v1.34 and only broke when you updated to v1.35, that's not the case, and the capture that you uploaded and said was working in v1.34, it never worked?

In that case I don't think there's a RenderDoc bug here, only the broken shaders. It sounds like you changed DXC versions and the new DXC version emits broken shaders.

For the future please be more careful when reporting bugs and don't provide incorrect information as it wastes time and causes confusion.

**Comment by Goshido** [comment]
@baldurk if I understood correctly it's not _RenderDoc_ parsing issue. So I created the issue for _DXC_: [#6939](https://github.com/microsoft/DirectXShaderCompiler/issues/6939).
