### ISSUE TITLE
build problem: new compiler deprecates literal operator syntax

### ISSUE THREAD

**Issue by semenzato** [baldurk/renderdoc#3621]
## Description of Bug

Build is broken after compiler upgrade, due to tightening of `operator ""` syntax.

What I want to do: compile without errors.

What is actually happening:
```
renderdoc/api/replay/rdcstr.h:45:42: error: identifier '_lit' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
   45 |   friend constexpr rdcliteral operator"" _lit(const char *str, size_t len);
      |                               ~~~~~~~~~~~^~~~
      |                               operator""_lit
```

This is the compiler being used:
```
 -- The CXX compiler identification is Clang 21.0.0
-- The C compiler identification is Clang 21.0.
```

## Steps to reproduce

Compile with Clang 21.0.0.

## Environment

* RenderDoc version: 1.27
* Operating System: Linux
* Graphics API: N/A

I don't expect that more details are useful here---please let me know if I am wrong.

If it helps, here's the fix:
```
diff --git a/renderdoc/api/replay/rdcstr.h b/renderdoc/api/replay/rdcstr.h
index 1234..5678 100644
--- a/renderdoc/api/replay/rdcstr.h
+++ b/renderdoc/api/replay/rdcstr.h
@@ -42,7 +42,7 @@
   size_t len;
 
   // make the literal operator a friend so it can construct fixed strings. No-one else can.
-  friend constexpr rdcliteral operator"" _lit(const char *str, size_t len);
+  friend constexpr rdcliteral operator""_lit(const char *str, size_t len);
 
   // similarly friend inflexible strings to allow them to decompose to a literal
   friend class rdcinflexiblestr;
@@ -57,7 +57,7 @@
   const char *end() const { return str + len; }
 };
 
-inline constexpr rdcliteral operator"" _lit(const char *str, size_t len)
+inline constexpr rdcliteral operator""_lit(const char *str, size_t len)
 {
   return rdcliteral(str, len);
 }

diff --git a/util/test/demos/3rdparty/fmt/format.h b/util/test/demos/3rdparty/fmt/format.h
index 1234..5678 100644
--- a/util/test/demos/3rdparty/fmt/format.h
+++ b/util/test/demos/3rdparty/fmt/format.h
@@ -586,7 +586,7 @@
 
 #if FMT_USE_USER_DEFINED_LITERALS
 inline namespace literals {
-FMT_DEPRECATED inline basic_string_view<internal::char8_type> operator"" _u(
+FMT_DEPRECATED inline basic_string_view<internal::char8_type> operator""_u(
     const char* s, std::size_t n) {
   return {reinterpret_cast<const internal::char8_type*>(s), n};
 }
@@ -3577,11 +3577,11 @@
     std::string message = "The answer is {}"_format(42);
   \endrst
  */
-FMT_CONSTEXPR internal::udl_formatter<char> operator"" _format(const char* s,
+FMT_CONSTEXPR internal::udl_formatter<char> operator""_format(const char* s,
                                                                std::size_t n) {
   return {{s, n}};
 }
-FMT_CONSTEXPR internal::udl_formatter<wchar_t> operator"" _format(
+FMT_CONSTEXPR internal::udl_formatter<wchar_t> operator""_format(
     const wchar_t* s, std::size_t n) {
   return {{s, n}};
 }
@@ -3597,11 +3597,11 @@
     fmt::print("Elapsed time: {s:.2f} seconds", "s"_a=1.23);
   \endrst
  */
-FMT_CONSTEXPR internal::udl_arg<char> operator"" _a(const char* s,
+FMT_CONSTEXPR internal::udl_arg<char> operator""_a(const char* s,
                                                     std::size_t n) {
   return {{s, n}};
 }
-FMT_CONSTEXPR internal::udl_arg<wchar_t> operator"" _a(const wchar_t* s,
+FMT_CONSTEXPR internal::udl_arg<wchar_t> operator""_a(const wchar_t* s,
                                                        std::size_t n) {
   return {{s, n}};
 }
diff --git a/renderdoc/3rdparty/catch/official/catch.hpp b/renderdoc/3rdparty/catch/official/catch.hpp
index 1234..5678 100644
--- a/renderdoc/3rdparty/catch/official/catch.hpp
+++ b/renderdoc/3rdparty/catch/official/catch.hpp
@@ -688,12 +688,12 @@
     auto operator += ( std::string& lhs, StringRef const& sr ) -> std::string&;
     auto operator << ( std::ostream& os, StringRef const& sr ) -> std::ostream&;
 
-    constexpr auto operator "" _sr( char const* rawChars, std::size_t size ) noexcept -> StringRef {
+    constexpr auto operator""_sr( char const* rawChars, std::size_t size ) noexcept -> StringRef {
         return StringRef( rawChars, size );
     }
 } // namespace Catch
 
-constexpr auto operator "" _catch_sr( char const* rawChars, std::size_t size ) noexcept -> Catch::StringRef {
+constexpr auto operator""_catch_sr( char const* rawChars, std::size_t size ) noexcept -> Catch::StringRef {
     return Catch::StringRef( rawChars, size );
 }
 
@@ -3266,8 +3266,8 @@
 } // end namespace Detail
 
 namespace literals {
-    Detail::Approx operator "" _a(long double val);
-    Detail::Approx operator "" _a(unsigned long long val);
+    Detail::Approx operator""_a(long double val);
+    Detail::Approx operator""_a(unsigned long long val);
 } // end namespace literals
 
 template<>
@@ -8006,10 +8006,10 @@
 } // end namespace Detail
 
 namespace literals {
-    Detail::Approx operator "" _a(long double val) {
+    Detail::Approx operator""_a(long double val) {
         return Detail::Approx(val);
     }
-    Detail::Approx operator "" _a(unsigned long long val) {
+    Detail::Approx operator""_a(unsigned long long val) {
         return Detail::Approx(val);
     }
 } // end namespace literals

diff --git a/qrenderdoc/3rdparty/catch/official/catch.hpp b/qrenderdoc/3rdparty/catch/official/catch.hpp
index 1234..5678 100644
--- a/qrenderdoc/3rdparty/catch/official/catch.hpp
+++ b/qrenderdoc/3rdparty/catch/official/catch.hpp
@@ -688,12 +688,12 @@
     auto operator += ( std::string& lhs, StringRef const& sr ) -> std::string&;
     auto operator << ( std::ostream& os, StringRef const& sr ) -> std::ostream&;
 
-    constexpr auto operator "" _sr( char const* rawChars, std::size_t size ) noexcept -> StringRef {
+    constexpr auto operator""_sr( char const* rawChars, std::size_t size ) noexcept -> StringRef {
         return StringRef( rawChars, size );
     }
 } // namespace Catch
 
-constexpr auto operator "" _catch_sr( char const* rawChars, std::size_t size ) noexcept -> Catch::StringRef {
+constexpr auto operator""_catch_sr( char const* rawChars, std::size_t size ) noexcept -> Catch::StringRef {
     return Catch::StringRef( rawChars, size );
 }
 
@@ -3266,8 +3266,8 @@
 } // end namespace Detail
 
 namespace literals {
-    Detail::Approx operator "" _a(long double val);
-    Detail::Approx operator "" _a(unsigned long long val);
+    Detail::Approx operator""_a(long double val);
+    Detail::Approx operator""_a(unsigned long long val);
 } // end namespace literals
 
 template<>
@@ -8006,10 +8006,10 @@
 } // end namespace Detail
 
 namespace literals {
-    Detail::Approx operator "" _a(long double val) {
+    Detail::Approx operator""_a(long double val) {
         return Detail::Approx(val);
     }
-    Detail::Approx operator "" _a(unsigned long long val) {
+    Detail::Approx operator""_a(unsigned long long val) {
         return Detail::Approx(val);
     }
 } // end namespace literals

diff --git a/renderdoc/3rdparty/half/half.hpp b/renderdoc/3rdparty/half/half.hpp
index 1234..5678 100644
--- a/renderdoc/3rdparty/half/half.hpp
+++ b/renderdoc/3rdparty/half/half.hpp
@@ -443,7 +443,7 @@
 	/// ~~~~
 	namespace literal
 	{
-		half operator "" _h(long double);
+		half operator""_h(long double);
 	}
 #endif
 
@@ -2269,7 +2269,7 @@
 		friend struct std::hash<half>;
 	#endif
 	#if HALF_ENABLE_CPP11_USER_LITERALS
-		friend half literal::operator "" _h(long double);
+		friend half literal::operator""_h(long double);
 	#endif
 	#endif
 	};
@@ -2284,7 +2284,7 @@
 		/// \param value literal value
 		/// \return half with of given value (possibly rounded)
 		/// \exception FE_OVERFLOW, ...UNDERFLOW, ...INEXACT according to rounding
-		inline half operator "" _h(long double value) { return half(detail::binary, detail::float2half<half::round_style>(value)); }
+		inline half operator""_h(long double value) { return half(detail::binary, detail::float2half<half::round_style>(value)); }
 	}
 #endif
```

**Comment by baldurk** [comment]
I assume you made a typo as llvm 20 is the most recent version released, but I was able to reproduce the warning there. That commit will silence it.

If you are building RenderDoc locally I would recommend building in release. Not only will that apply compiler optimisations but it will disable warnings-as-errors which is intended for RenderDoc developers not average users.

**Comment by semenzato** [comment]
Thanks!  I copy-pasted the compiler version from the build output (with the oddly-missing final 0, I went back and checked).  This is for a Gentoo build, ChromeOS really, so I don't know if we modified the ebuild locally, and I also don't know if we maintain our own version of clang, everything is possible ;)  But in any case I suspect that we'll keep warnings as errors, and patch the source for now.
