### ISSUE TITLE
does not build - error: ‘isinf’ was not declared in this scope

### ISSUE THREAD

**Issue by Marqin** [baldurk/renderdoc#187]
Does not build on Arch Linux ( g++ 5.3 )

Problem is with file `renderdoc/3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp`
and it looks like it's because you use `isinf` instead of `std::isinf` ( because `isinf` is in `std` namespace ) - http://en.cppreference.com/w/cpp/numeric/math/isinf

Full error:

```
g++ -c -Wall -Werror -Wno-unused -Wno-unknown-pragmas -fPIC -DLINUX -DRENDERDOC_PLATFORM=linux -DRENDERDOC_EXPORTS -DGLSLANG_OSINCLUDE_UNIX -DGIT_COMMIT_HASH="\"`git rev-parse HEAD`\"" -I../../../ -I../../../3rdparty/ -std=c++11 -g -Wno-reorder -fvisibility=hidden -fvisibility-inlines-hidden -c -o .obj/glslang/glslang/MachineIndependent/intermOut.o ../../../3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp
../../../3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp: In function ‘bool {anonymous}::is_positive_infinity(double)’:
../../../3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp:54:17: error: ‘isinf’ was not declared in this scope
   return isinf(x) && (x >= 0);
                 ^
../../../3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp:54:17: note: suggested alternative:
In file included from /usr/include/c++/5.3.0/random:38:0,
                 from /usr/include/c++/5.3.0/bits/stl_algo.h:66,
                 from /usr/include/c++/5.3.0/algorithm:62,
                 from ../../../3rdparty/glslang/glslang/MachineIndependent/../Include/../Include/Common.h:78,
                 from ../../../3rdparty/glslang/glslang/MachineIndependent/../Include/intermediate.h:49,
                 from ../../../3rdparty/glslang/glslang/MachineIndependent/localintermediate.h:38,
                 from ../../../3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp:37:
/usr/include/c++/5.3.0/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
```

**Comment by baldurk** [comment]
This code is from upstream [glslang](https://github.com/KhronosGroup/glslang). I enable -Wall and -Werror though so I tend to catch some issues that don't show up there.

It looks like the linux system I use to do nightly build tests is only running gcc 4.9.2 so I guess it's not picking up the same warnings as a newer version. I'll try and rustle up something newer and push any warning fixes upstream if possible.

**Comment by Marqin** [comment]
Also, this little patch/diff fixes problem:
```
 renderdoc/3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/renderdoc/3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp b/renderdoc/3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp
index dd0769f..c06a0a1 100644
--- a/renderdoc/3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp
+++ b/renderdoc/3rdparty/glslang/glslang/MachineIndependent/intermOut.cpp
@@ -48,7 +48,7 @@ namespace {
 bool is_positive_infinity(double x) {
 #ifdef _MSC_VER
   return _fpclass(x) == _FPCLASS_PINF;
-#elif defined __ANDROID__
+#elif defined __ANDROID__ || defined __linux__
   return std::isinf(x) && (x >= 0);
 #else
   return isinf(x) && (x >= 0);
```

**Comment by baldurk** [comment]
Right that looks reasonable to me. I don't make glslang changes directly on this repository to make things easier, I have a separate fork that has my local delta from upstream. I try and minimise it when possible, so I will try and do a PR to that repo with any fixes.

**Comment by Marqin** [comment]
I have this error also in original glslang, so I've made issue and pull request there - https://github.com/KhronosGroup/glslang/issues/171

**Comment by baldurk** [comment]
I'll update glslang at the start of next week, and I'll roll in your fix to my fork's local changes if it hasn't been merged upstream.

**Comment by Marqin** [comment]
On 23.02.2016 23:38, Baldur Karlsson wrote:
>
> I'll update glslang at the start of next week, and I'll roll in your
> fix to my fork's local changes if it hasn't been merged upstream.
>

Ok, I've already put that patch in package I'm maintaining.

**Comment by baldurk** [comment]
I've now pushed an updated copy of glslang to renderdoc, which should include this fix (and another warning fix I encountered - I've made a pull request for the warning fixes I had locally).
