### ISSUE TITLE
Please update swig version to not depend on deprecated PCRE

### ISSUE THREAD

**Issue by elmarco** [baldurk/renderdoc#3175]
## Description

We are trying to get renderdoc back in Fedora.

Unfortunately, the dependency on swig & pcre is problematic, as PCRE is deprecated, see also:
https://bugzilla.redhat.com/show_bug.cgi?id=2254392#c2

I would help if you could update the swig version to latest that can use pcre2, or make building possible  --without-pcre

## Environment

RenderDoc version: 1.30, git
Operating System: Fedora

**Comment by baldurk** [comment]
Building without pcre is not possible as it's required for the bindings generation. This is a duplicate of #2945 and I'm still not convinced that this is an important enough thing to make changes to fix.

I'll think about if there's a reasonable compromise here, ideally one that only impacts people on these distros who can't get the normal library, but please note that I'm not responsible for any distro packages and addressing distro-specific issues is not a high priority for me.

**Comment by baldurk** [comment]
Can you clarify since I talked to someone on discord and it seems like I might have gotten the wrong impression - is this distro removing the package entirely so it would be impossible to follow the build instructions, or is it just a limitation of the distro's packaging rules that don't allow it to be used?

**Comment by elmarco** [comment]
Distros are moving away  from / retiring pcre (see for Fedora https://fedoraproject.org/wiki/Changes/PcreDeprecation)

And distros don't like for packages to bundle other projects/sources either, and go to great length to prevent it (see also https://fedoraproject.org/wiki/Bundled_Libraries)

**Comment by baldurk** [comment]
OK I understand, reading that it looks like the package hasn't been removed and you can still build RenderDoc on fedora then. That is the main thing I'm concerned about - if there are issues with distro packaging rules that's not something I feel gives sufficient value to the project to justify changing otherwise working and stable code.

If the package is removed entirely in future then I can look at making some changes to ensure RenderDoc can still be compiled.

**Comment by elmarco** [comment]
No, it's not ok for Fedora, (the package has been retired due to various build issues, we are trying to get it back). https://bugzilla.redhat.com/show_bug.cgi?id=2254392#c2

Since SWIG is a build time only dependency iiuc, can't you ship the generated files rather than requiring SWIG & PCRE? (it's not great, but that removes the burdden from the distro)

**Comment by baldurk** [comment]
As far as I could see from your links pcre is still available on fedora and so you can still compile RenderDoc. Several posts explicitly said they were not discussing removing the package (at least not currently).

It is a build time dependency yes. That may be possible though it would require changes, so I do not plan to do that for the same reasoning as above. It wouldn't be my preferred solution if it was impossible to compile swig normally on some distros in future.

**Comment by RogueScholar** [comment]
@baldurk: I believe the time has arrived that movement on this issue may be required. RenderDoc was already [removed entirely from Debian Testing](https://tracker.debian.org/news/1445223/renderdoc-removed-from-testing/), a/k/a Debian 13 "Trixie," nearly a year ago (2023-07-17) due to this issue. This effectively means that current Debian 12 "Bookworm" release will be the last with renderdoc in the Debian package archives. Because of this, RenderDoc was also [removed from the Ubuntu package archives for the 24.04 LTS release](https://launchpad.net/ubuntu/+source/renderdoc/+publishinghistory) a few months ago.

I didn't realize RenderDoc had been uninstalled from my system when I upgraded to 24.04 until I went to go use it today and then uncovered all of this after I wasn't able to simply reinstall it with `apt`. With the [Debian import freeze for Ubuntu 24.10](https://discourse.ubuntu.com/t/oracular-oriole-release-schedule/36460) roughly five weeks away, that doesn't leave much time to rectify the situation. Did you ever reach a conclusion as to whether you are willing to port to PCRE2 in the first place?

**Comment by theoparis** [comment]
I just ran into this issue on MacOS as well, except using `-DRENDERDOC_SWIG_PACKAGE=https://github.com/swig/swig/archive/master.tar.gz` didn't work either because pcre.h doesn't exist (pcre2.h does though). I had to symlink pcre2.h to pcre.h and pcre2-config to pcre-config to get it to continue compiling. 

Additionally, some deprecated and broken swig command line options seem to be used:
```
Deprecated command line option: -modern. Ignored, this option is now always on.
Deprecated command line option: -modernargs. Ignored, this option is now always on.
Deprecated command line option: -fastunpack. Ignored, this option is now always on.
Deprecated command line option: -py3. Ignored, this option is no longer supported.
swig error : Unrecognized option -enumclass
Use 'swig -help' for available options.
```

The python bindings seem to be broken with python 3.13 installed from homebrew as well:
```
renderdoc_python.cxx:266771:5: error: cannot initialize a member subobject of type 'lenfunc' (aka 'long (*)(_object *)') with an lvalue of type 'Py_ssize_t (PyObject *, Py_ssize_t, PyObject *)' (aka 'long (_object *, long, _object *)'): different number of parameters (1 vs 3)
 266771 |     length_StructuredObjectList,            /* sq_length */
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Unfortunately I ended up giving up and disabling renderdoc-rs in someone's rust project for the time being since it is such a pain to get working. It would be great if these issues can be resolved in the future

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
