### ISSUE TITLE
Queue Capture Frame stopped working in 1.14

### ISSUE THREAD

**Issue by tuket** [baldurk/renderdoc#2289]
## Description

I have noticed that in version 1.14 the "Queue Capture" checkbox has stopped working. When you mark it and set a few frames, the application crashes and there are no captures in RenderDoc. I'm using RenderDoc to debug OpenGL applications. Capturing with F12 works fine.

![image](https://user-images.githubusercontent.com/4165974/121145084-e296e700-c83e-11eb-9981-b75571b90949.png)

There is an error in the log:

```
Core 15208 07:53:31 core.cpp(770) Error Couldn't find matching frame capturer for device 0000000000010002 window 0000000000000000 from 0 device frame capturers and 0 frame capturers
```

I will attach the whole log file too: [RenderDoc_2021.06.08_07.53.05.log](https://github.com/baldurk/renderdoc/files/6614563/RenderDoc_2021.06.08_07.53.05.log)

## Steps to reproduce

1. Open RenderDoc
2. Set the path to your OpenGL executable
3. Mark the "Queue Capture" checkbox, and set the number of frames (starting from 0)
4. Click "Launch"
5. The application crashes and no captures are recorded in RenderDoc.

## Environment

* RenderDoc version: 1.14
* Operating System: Windows 10
* Graphics API: OpenGL
* GPU: GTX 960M

**Comment by baldurk** [comment]
This was fixed in 6ce0b9a0876b87d3d8903f3393e4e87c7f656fa9. Note that specifically this only happened if you queued capture from frame 0 in an OpenGL application exactly as you describe.
